# Imports

# Fonction division pouvant provoquer une erreur

# Fonction principale
def main():
    pass
        # provocation de l'erreur de division par 0

        # sys.exc_info() retourne un tuple (type, value, traceback) de la dernière exception attrapée.

        # recupere le traceback pour faire l'analyse post mortem

# Appel de la fonction principale
if __name__ == "__main__":
    main()
